# #
# 功能：集群方式启动redis服务
# 使用：
#   - docker-compose up -d
# 默认密码：123456
# #
# 参考链接：https://blog.51cto.com/u_15127508/4395149
version: '2'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --port 6379 --requirepass 123456  --appendonly yes
    ports:
      - '6379:6379'
    networks:
      net:
        ipv4_address: 172.19.0.3

# 创建桥接网络
networks:
  # 参考：https://www.jianshu.com/p/d70c61d45364
  net:
    driver: bridge
    # external: true
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          # 网关
          gateway: 172.19.0.1
