##
## 功能：redis主从集群 1主2从
## 使用：
##   - docker-compose up -d
## 默认密码：123456
##
## 参考链接：https://blog.51cto.com/u_15127508/4395149
## 参考：http://t.zoukankan.com/JulianHuang-p-12650721.html
version: '2'
services:
  redis-master-6380:
    image: redis:latest
    container_name: redis-master-6380
    restart: always
    command: redis-server --port 6380 --requirepass 123456  --appendonly yes
    ports:
      - "6380:6380"
    networks:
      net:
        ipv4_address: 172.19.0.3

  redis-slave-6381:
    image: redis:latest
    container_name: redis-slave-6381
    restart: always
    command: redis-server --slaveof redis-master-6380 6380 --port 6381  --requirepass 123456 --masterauth 123456  --appendonly yes
    ports:
      - "6381:6381"
    networks:
      net:
        ipv4_address: 172.19.0.4

  redis-slave-6382:
    image: redis:latest
    container_name: redis-slave-6382
    restart: always
    command: redis-server --slaveof redis-master-6380 6380 --port 6382  --requirepass 123456 --masterauth 123456 --appendonly yes
    ports:
      - "6382:6382"
    networks:
      net:
        ipv4_address: 172.19.0.5

## 创建桥接网络
networks:
  ## 桥接网络名称，配合文件前缀，最后为dev_test_env_net  参考：https://www.jianshu.com/p/d70c61d45364
  net:
    driver: bridge
    # external: true
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          ## 网关
          gateway: 172.19.0.1