#!/usr/bin/env node

/**
 * 功能：构建Docker镜像
 * 使用：
 *  - ./scripts/bundle
 *  - ./scripts/bundle --proxy
 */

import {
  OPEN_SOURCE_ADDRESS,
  OPEN_SOURCE_AUTHOR,
  VipDocker,
  VipGit,
  VipNodeJS,
  VipPackageJSON,
} from '@142vip/utils'

(async () => {
  try {
    // 获取package.json文件
    const { name, version, description } = VipPackageJSON.getPackageJSON()

    // 镜像地址
    const imageName = `${OPEN_SOURCE_ADDRESS.DOCKER_ALIYUNCS_VIP}/docs:${name}-${version}`

    // 最近一次提交信息
    const gitHash = VipGit.getFirstCommitHash()

    // 构建镜像
    await VipDocker.buildImage({
      imageName,
      buildArgs: [
        // 参数中是否包含 --proxy
        ['NEED_PROXY', VipNodeJS.getProcessArgv().includes('--proxy')],
        ['APP_NAME', name],
        ['APP_VERSION', version],
        ['APP_DESCRIPTION', description],
        ['AUTHOR', OPEN_SOURCE_AUTHOR.name],
        ['EMAIL', OPEN_SOURCE_AUTHOR.email],
        ['HOME_PAGE', OPEN_SOURCE_AUTHOR.homePage],
        ['GIT_HASH', gitHash],
      ],
      memory: 20000,
      push: true,
      delete: true,
      logger: true,
    })
  }
  catch (e) {
    console.log('异常信息:', e)
  }
})()
