#!/bin/bash
##
## 依赖安装脚本
## 使用:
##   ./scripts/ci
##


NPM_REGISTRY="https://registry.npmmirror.com"

## 获取所有参数
echo "运行命令: COREPACK_NPM_REGISTRY=$NPM_REGISTRY corepack enable pnpm && pnpm i --registry $NPM_REGISTRY --frozen-lockfile $*"

# 安装pnpm版本
COREPACK_NPM_REGISTRY=$NPM_REGISTRY corepack enable pnpm


# 安装项目依赖 -w -F @142vip/fairy-cli
pnpm i  --registry $NPM_REGISTRY --frozen-lockfile "$@"
