#!/bin/bash

##
## 自动格式化
##  - 代码
##  - markdown文档
## 使用:
#    - ./scripts/lint
## 参考链接：
##   - https://eslint.org/docs/latest/use/getting-started
##   - https://github.com/igorshubovych/markdownlint-cli
##

# ESLint格式化代码
$(pnpm bin)/eslint --fix --ext .js,.ts,.vue --ignore-path .gitignore .

# markdown-cli格式化markdown 文档
$(pnpm bin)/markdownlint '**/*.md'  -c .markdownlint.js -p .markdownlintignore --fix

