#!/bin/bash
#
# 版本发布脚本
# 链接：https://jstools.dev/version-bump-prompt/
# 使用:
#    - ./scripts/release
#

# 获取当前分支名称
readonly currentBranch=$(git rev-parse --abbrev-ref HEAD)

# 判断分支名称
if [ "$currentBranch" = "next" ]; then
    # git提交记录，仓库版本更新
    npx bumpx --preid alpha --changelog --commit "chore(release): publish v%s" --execute="git add CHANGELOG.md" --all
else
  echo "当前分支是：$currentBranch ，版本迭代允许在next分支操作，并推送到远程！！！"
fi

# 直接快速生成CHANGELOG文档
#npx bumpx --preid alpha --changelog --commit "chore(release): publish v%s" --execute="git add CHANGELOG.md" --all --no-tag --no-commit --no-push

