# 部署到服务器
name: Deploy-ESC

on:
  push: # 推送的时候触发
      branches:
        - master
  workflow_dispatch:

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  UserName: mmdapl


jobs:
  Deploy-ESC:
    name: "部署到ESC"
    runs-on: ubuntu-latest
    if: github.repository == '142vip/JavaScriptCollection'
    permissions:
      actions: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Current Version
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version

        # 拉取镜像，更新服务
      - name: Pull Image And Update ESC
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.Server_Host }}
          port: ${{ secrets.Server_Port }}
          username: ${{ secrets.Server_UserName }}
          password: ${{ secrets.Server_Password }}
          script: |
            docker images 
            echo "-----------正在运行的服务--------" 
            docker ps
            cd /service_env/ && git reset --hard && git pull origin main 
            bash ./scripts/book_doc.deploy.sh jsc ${{steps.version.outputs.value}} 
